---

- name: To check if pull-secrets exists
  stat:
    path: "{{ dir_path }}/pull-secret.txt"
  register: secret_file
   
- name: hard link the pull-secret file
  file:
    src: "{{ dir_path }}/pull-secret.txt"
    dest: "{{ dir_path }}//ocp-upi-powervs-pod/pull-secret.txt"
    state: hard
  when: secret_file.stat.exists
    
- name: To check if var file exists
  stat:
    path: "{{ dir_path }}/var.tfvars"
  #  path: "{{ dir_path }}/ocp-variables"
  register: variable_file 
    
- name: hard link the variables file file
  file:
    src: "{{ dir_path }}/var.tfvars"
    dest: "{{ dir_path }}/ocp-upi-powervs-pod/var.tfvars"
    state: hard
  when: variable_file.stat.exists

#- name: Map var.tfvars to ocp-variables
