---

- name: Setup Repository
  hosts: webhost
  roles:
  - repo-setup

- name: Docker image
  hosts: webhost
  roles:
  - docker-img

- name: Docker image
  hosts: webhost
  roles:
  - ocp-configurations

- name: Create cluster
  hosts: webhost
  roles:
  - script-install

